import { Dish, DishKind, Meal } from "./types";

// YouTube search fallback URL from a dish name.
export function youtubeSearch(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " recipe")}`;
}

// On-demand food-photo URL keyed by dish name. Always resolves; the UI falls
// back to an emoji tile if the image fails to load. Override per dish by
// setting imageUrl in the Library.
export function dishImage(name: string): string {
  const prompt = `authentic south indian tamil ${name}, plated dish, food photography, natural light, top view`;
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=600&height=400&nologo=true`;
}

function mk(
  id: string,
  name: string,
  nameTamil: string,
  meals: Meal[],
  kind: DishKind,
  proteinGrams: number,
  ingredients: string[],
  steps: string[]
): Dish {
  return {
    id, name, nameTamil, meals, kind, ingredients, steps, proteinGrams,
    youtubeUrl: youtubeSearch(name), imageUrl: dishImage(name), isCustom: false,
  };
}

// Protein values are per-serving estimates (approximate). Recipes are concise,
// best-effort guides. Verify before cooking.

const BREAKFAST: Dish[] = [
  mk("idli", "Idli", "இட்லி", ["breakfast"], "main", 6,
    ["2 cups idli rice", "1 cup urad dal", "1 tsp fenugreek", "Salt"],
    ["Soak rice and dal 5 hours, grind, ferment overnight.", "Add salt, pour into moulds.", "Steam 10 to 12 minutes.", "Serve with sambar and chutney."]),
  mk("plain-dosa", "Plain Dosa", "தோசை", ["breakfast"], "main", 7,
    ["3 cups dosa rice", "1 cup urad dal", "1 tsp fenugreek", "Salt", "Oil"],
    ["Soak, grind and ferment the batter.", "Spread thin on a hot tawa.", "Drizzle oil, cook till crisp.", "Serve with chutney."]),
  mk("masala-dosa", "Masala Dosa", "மசாலா தோசை", ["breakfast"], "main", 9,
    ["Dosa batter", "Potatoes", "Onion", "Turmeric", "Mustard, curry leaves"],
    ["Make a potato masala with onion and turmeric.", "Spread dosa on tawa, crisp it.", "Place masala inside and fold.", "Serve with chutney."]),
  mk("rava-dosa", "Rava Dosa", "ரவா தோசை", ["breakfast"], "main", 6,
    ["1 cup rava", "0.5 cup rice flour", "Green chilli, cumin", "Onion", "Salt"],
    ["Mix a thin pourable batter, rest 20 minutes.", "Sprinkle batter on hot tawa from edges in.", "Drizzle oil, cook crisp.", "Serve hot."]),
  mk("ven-pongal", "Ven Pongal", "வெண் பொங்கல்", ["breakfast"], "main", 9,
    ["1 cup rice", "0.5 cup moong dal", "Pepper, cumin", "Ginger, cashews", "Ghee"],
    ["Roast dal, pressure cook with rice.", "Temper pepper, cumin, ginger, cashews in ghee.", "Mix in, add salt.", "Serve hot."]),
  mk("sakkarai-pongal", "Sakkarai Pongal", "சக்கரை பொங்கல்", ["breakfast"], "main", 7,
    ["1 cup rice", "0.5 cup moong dal", "Jaggery", "Ghee, cashews", "Cardamom"],
    ["Cook rice and dal soft.", "Melt jaggery, add to the rice.", "Roast cashews in ghee, add with cardamom.", "Serve warm."]),
  mk("idiyappam", "Idiyappam", "இடியாப்பம்", ["breakfast"], "main", 6,
    ["2 cups rice flour", "Hot water", "Salt", "Oil"],
    ["Make a soft dough with hot water and salt.", "Press through the idiyappam mould onto plates.", "Steam 6 to 8 minutes.", "Serve with coconut milk or kurma."]),
  mk("aappam", "Aappam", "ஆப்பம்", ["breakfast"], "main", 6,
    ["2 cups raw rice", "Cooked rice", "Coconut", "Yeast or soda", "Salt"],
    ["Grind rice and coconut, ferment.", "Pour into a hot appam pan and swirl.", "Cover and cook till edges crisp.", "Serve with coconut milk."]),
  mk("uttapam", "Uttapam", "ஊத்தப்பம்", ["breakfast"], "main", 7,
    ["Dosa batter", "Onion", "Tomato", "Green chilli", "Coriander"],
    ["Pour thick batter on tawa.", "Top with chopped onion, tomato, chilli.", "Drizzle oil, cook both sides.", "Serve with chutney."]),
  mk("onion-uttapam", "Onion Uttapam", "வெங்காய ஊத்தப்பம்", ["breakfast"], "main", 7,
    ["Dosa batter", "Onion", "Green chilli", "Curry leaves", "Oil"],
    ["Spread thick batter on tawa.", "Press on plenty of onion and chilli.", "Cook till golden and soft.", "Serve with chutney."]),
  mk("pesarattu", "Pesarattu", "பெசரட்டு", ["breakfast"], "main", 14,
    ["1 cup whole green gram", "Green chilli", "Ginger", "Salt", "Oil"],
    ["Soak green gram 4 hours, grind to batter.", "Spread thin on a hot tawa.", "Drizzle oil, cook both sides.", "Serve with ginger chutney."]),
  mk("adai", "Adai", "அடை", ["breakfast"], "main", 15,
    ["Toor, chana, urad dal", "Raw rice", "Red chilli", "Asafoetida", "Curry leaves"],
    ["Soak dals and rice, grind coarse.", "Add chilli, asafoetida, curry leaves.", "Spread thick on tawa, cook crisp.", "Serve with avial or jaggery."]),
  mk("rava-upma", "Rava Upma", "ரவா உப்புமா", ["breakfast"], "main", 6,
    ["1 cup rava", "Onion, green chilli", "Mustard, urad dal", "Curry leaves", "2 cups water"],
    ["Roast rava, set aside.", "Temper spices, saute onion.", "Add water, then rava, stir.", "Cook till fluffy."]),
  mk("semiya-upma", "Semiya Upma", "செமியா உப்புமா", ["breakfast"], "main", 6,
    ["1 cup vermicelli", "Onion, carrot, peas", "Mustard, urad dal", "Curry leaves", "Water"],
    ["Roast vermicelli lightly.", "Temper, saute onion and vegetables.", "Add water and vermicelli, cook covered.", "Fluff and serve."]),
  mk("arisi-upma", "Arisi Upma", "அரிசி உப்புமா", ["breakfast"], "main", 7,
    ["1 cup raw rice", "Toor dal", "Pepper, cumin", "Coconut", "Curry leaves"],
    ["Coarsely grind rice with pepper and cumin.", "Roast with dal.", "Temper and cook with water till soft.", "Garnish coconut, serve."]),
  mk("aval-upma", "Aval Upma", "அவல் உப்புமா", ["breakfast"], "main", 5,
    ["2 cups thick poha", "Onion, green chilli", "Mustard, peanuts", "Turmeric", "Curry leaves"],
    ["Rinse poha, drain.", "Temper, saute onion, peanuts, turmeric.", "Add poha, mix gently, warm through.", "Serve."]),
  mk("kuzhi-paniyaram", "Kuzhi Paniyaram", "குழி பணியாரம்", ["breakfast"], "main", 7,
    ["Dosa batter", "Onion", "Green chilli", "Mustard, curry leaves", "Oil"],
    ["Temper onion and chilli, mix into batter.", "Pour into a paniyaram pan.", "Cook covered, flip till golden.", "Serve with chutney."]),
  mk("medhu-vada", "Medhu Vada", "மெது வடை", ["breakfast"], "main", 11,
    ["1 cup urad dal", "Pepper, cumin", "Onion, curry leaves", "Salt", "Oil"],
    ["Soak dal, grind thick and fluffy.", "Add pepper, cumin, onion.", "Shape with a hole, deep fry.", "Serve with chutney and sambar."]),
  mk("sambar-vada", "Sambar Vada", "சாம்பார் வடை", ["breakfast"], "main", 13,
    ["Medhu vada", "Sambar", "Onion", "Coriander", "Oil"],
    ["Make and fry medhu vada.", "Soak the vada briefly in hot sambar.", "Top with onion and coriander.", "Serve hot."]),
  mk("ragi-dosa", "Ragi Dosa", "ராகி தோசை", ["breakfast"], "main", 7,
    ["1 cup ragi flour", "Rice flour", "Onion, chilli", "Cumin", "Salt"],
    ["Mix a thin batter, rest 15 minutes.", "Pour and spread on hot tawa.", "Drizzle oil, cook crisp.", "Serve with chutney."]),
  mk("set-dosa", "Set Dosa", "செட் தோசை", ["breakfast"], "main", 7,
    ["Dosa batter with curd", "Baking soda pinch", "Salt", "Oil"],
    ["Loosen batter with curd, rest.", "Pour small thick rounds on tawa.", "Cook soft and spongy, do not flip hard.", "Serve in sets with chutney."]),
  mk("godhumai-dosa", "Wheat Dosa", "கோதுமை தோசை", ["breakfast"], "main", 8,
    ["1 cup wheat flour", "Onion, chilli", "Cumin", "Curry leaves", "Salt"],
    ["Whisk a thin pourable batter.", "Pour from edges on hot tawa.", "Drizzle oil, crisp it.", "Serve with chutney."]),
  mk("kambu-dosa", "Kambu Dosa", "கம்பு தோசை", ["breakfast"], "main", 9,
    ["Pearl millet flour", "Dosa rice", "Urad dal", "Salt", "Oil"],
    ["Grind and ferment millet with rice and dal.", "Spread on hot tawa.", "Cook crisp with oil.", "Serve with chutney."]),
  mk("thinai-pongal", "Thinai Pongal", "தினை பொங்கல்", ["breakfast"], "main", 8,
    ["1 cup foxtail millet", "Moong dal", "Pepper, cumin", "Ginger, cashews", "Ghee"],
    ["Cook millet and dal soft.", "Temper pepper, cumin, cashews in ghee.", "Mix in with salt.", "Serve hot."]),
  mk("semiya-idli", "Semiya Idli", "செமியா இட்லி", ["breakfast"], "main", 6,
    ["Roasted vermicelli", "Rava", "Curd", "Carrot", "Eno"],
    ["Mix vermicelli, rava, curd and vegetables.", "Add eno just before steaming.", "Pour into moulds, steam 10 minutes.", "Serve with chutney."]),
  mk("rava-idli", "Rava Idli", "ரவா இட்லி", ["breakfast"], "main", 6,
    ["1 cup rava", "Curd", "Cashews", "Mustard, curry leaves", "Eno"],
    ["Roast rava, mix with curd.", "Temper cashews and spices, add.", "Add eno, pour into moulds.", "Steam 10 to 12 minutes."]),
  mk("kara-dosa", "Kara Dosa", "கார தோசை", ["breakfast"], "main", 7,
    ["Dosa batter", "Onion", "Red chilli paste", "Curry leaves", "Oil"],
    ["Spread dosa, smear chilli paste.", "Top with onion and curry leaves.", "Drizzle oil, crisp it.", "Serve hot."]),
  mk("podi-idli", "Podi Idli", "பொடி இட்லி", ["breakfast"], "main", 7,
    ["Mini idlis", "Idli podi", "Sesame oil", "Curry leaves", "Mustard"],
    ["Steam mini idlis.", "Temper mustard and curry leaves.", "Toss idlis with podi and oil.", "Serve warm."]),
  mk("ghee-roast-dosa", "Ghee Roast Dosa", "நெய் ரோஸ்ட் தோசை", ["breakfast"], "main", 8,
    ["Dosa batter", "Ghee", "Idli podi", "Salt"],
    ["Spread dosa very thin.", "Drizzle ghee generously.", "Sprinkle podi, roast crisp.", "Roll and serve."]),
  mk("rava-kichadi", "Rava Kichadi", "ரவா கிச்சடி", ["breakfast"], "main", 7,
    ["1 cup rava", "Mixed vegetables", "Onion, tomato", "Ginger, chilli", "Ghee"],
    ["Roast rava.", "Saute vegetables with ginger and chilli.", "Add water then rava, cook soft.", "Finish with ghee, serve."]),
];

const LUNCH_MAINS: Dish[] = [
  mk("sambar-sadam", "Sambar Sadam", "சாம்பார் சாதம்", ["lunch"], "main", 12,
    ["Rice", "Toor dal", "Mixed vegetables", "Sambar powder", "Tamarind"],
    ["Pressure cook rice, dal and vegetables.", "Add tamarind and sambar powder, simmer.", "Temper and add in.", "Serve with ghee and appalam."]),
  mk("curd-rice", "Thayir Sadam", "தயிர் சாதம்", ["lunch"], "main", 9,
    ["Cooked rice", "Curd", "Milk", "Ginger, chilli", "Mustard, curry leaves"],
    ["Mash rice, mix curd and milk.", "Temper mustard, chilli, ginger.", "Add tempering and salt.", "Serve chilled."]),
  mk("lemon-rice", "Elumichai Sadam", "எலுமிச்சை சாதம்", ["lunch"], "main", 7,
    ["Cooked rice", "Lemon", "Peanuts", "Chana, urad dal", "Turmeric"],
    ["Temper dals, peanuts, turmeric.", "Add to rice with salt.", "Squeeze lemon, mix.", "Serve warm."]),
  mk("tomato-rice", "Thakkali Sadam", "தக்காளி சாதம்", ["lunch"], "main", 8,
    ["Cooked rice", "Tomato", "Onion", "Chilli powder", "Garam masala"],
    ["Saute onion and tomato to a paste.", "Add spice powders, cook down.", "Mix in rice.", "Garnish coriander, serve."]),
  mk("coconut-rice", "Thengai Sadam", "தேங்காய் சாதம்", ["lunch"], "main", 8,
    ["Cooked rice", "Grated coconut", "Cashews", "Chana, urad dal", "Green chilli"],
    ["Temper dals, cashews, chilli.", "Add coconut, fry lightly.", "Mix into rice with salt.", "Serve."]),
  mk("puliyodarai", "Puliyodarai", "புளியோதரை", ["lunch"], "main", 8,
    ["Cooked rice", "Tamarind", "Peanuts", "Sesame, chilli", "Puli kaachal spices"],
    ["Make tangy tamarind paste with spices.", "Roast peanuts and sesame.", "Mix paste into rice.", "Rest and serve."]),
  mk("karuveppilai-sadam", "Curry Leaf Rice", "கருவேப்பிலை சாதம்", ["lunch"], "main", 8,
    ["Cooked rice", "Curry leaves", "Urad dal, chana", "Red chilli", "Coconut"],
    ["Roast curry leaves, dals, chilli, coconut.", "Grind to a coarse podi.", "Mix into rice with oil.", "Serve."]),
  mk("veg-biryani", "Vegetable Biryani", "காய்கறி பிரியாணி", ["lunch"], "main", 12,
    ["Basmati rice", "Mixed vegetables", "Onion, tomato", "Biryani masala", "Mint, curd"],
    ["Saute onion, tomato, vegetables with masala.", "Add curd and mint.", "Layer with par-cooked rice.", "Dum cook till done."]),
  mk("chicken-biryani", "Chicken Biryani", "சிக்கன் பிரியாணி", ["lunch"], "main", 30,
    ["Basmati rice", "Chicken", "Onion, tomato", "Biryani masala", "Curd, mint"],
    ["Marinate chicken in curd and spices.", "Saute onion, tomato, chicken.", "Layer with par-cooked rice.", "Dum cook 20 minutes."]),
  mk("mutton-biryani", "Mutton Biryani", "மட்டன் பிரியாணி", ["lunch"], "main", 33,
    ["Seeraga samba rice", "Mutton", "Onion, tomato", "Biryani masala", "Curd, mint"],
    ["Pressure cook mutton with spices.", "Build masala with onion and tomato.", "Layer with rice and mint.", "Dum cook till fragrant."]),
  mk("egg-biryani", "Egg Biryani", "முட்டை பிரியாணி", ["lunch"], "main", 18,
    ["Basmati rice", "Boiled eggs", "Onion, tomato", "Biryani masala", "Mint, curd"],
    ["Make a masala base, add curd and mint.", "Layer with par-cooked rice and eggs.", "Dum cook.", "Serve with raita."]),
  mk("vatha-kuzhambu-sadam", "Vatha Kuzhambu Rice", "வத்தக் குழம்பு சாதம்", ["lunch"], "main", 10,
    ["Rice", "Tamarind", "Sundakkai vathal", "Sambar powder", "Sesame oil"],
    ["Make tangy vatha kuzhambu with vathal.", "Temper in sesame oil.", "Simmer thick.", "Serve over rice."]),
  mk("vendhaya-kuzhambu-sadam", "Vendhaya Kuzhambu Rice", "வெந்தயக் குழம்பு சாதம்", ["lunch"], "main", 10,
    ["Rice", "Fenugreek", "Tamarind", "Sambar powder", "Garlic"],
    ["Roast and grind fenugreek.", "Cook tamarind base with garlic.", "Simmer to a thick kuzhambu.", "Serve over rice."]),
  mk("kara-kuzhambu-sadam", "Kara Kuzhambu Rice", "கார குழம்பு சாதம்", ["lunch"], "main", 11,
    ["Rice", "Tamarind", "Small onions", "Brinjal", "Sambar powder"],
    ["Saute onions and brinjal.", "Add tamarind and spices, simmer.", "Cook to a spicy gravy.", "Serve over rice."]),
  mk("mor-kuzhambu-sadam", "Mor Kuzhambu Rice", "மோர் குழம்பு சாதம்", ["lunch"], "main", 9,
    ["Rice", "Buttermilk", "Coconut, cumin", "Ash gourd or okra", "Curry leaves"],
    ["Grind coconut, cumin, chilli.", "Cook with vegetable, add buttermilk.", "Warm gently, do not boil hard.", "Serve over rice."]),
  mk("milagu-kuzhambu-sadam", "Milagu Kuzhambu Rice", "மிளகு குழம்பு சாதம்", ["lunch"], "main", 10,
    ["Rice", "Pepper", "Tamarind", "Toor dal", "Sesame oil"],
    ["Roast and grind pepper and dal.", "Cook with tamarind in sesame oil.", "Simmer thick and peppery.", "Serve over rice."]),
  mk("poondu-kuzhambu-sadam", "Poondu Kuzhambu Rice", "பூண்டு குழம்பு சாதம்", ["lunch"], "main", 10,
    ["Rice", "Garlic", "Tamarind", "Sambar powder", "Sesame oil"],
    ["Fry plenty of garlic in sesame oil.", "Add tamarind and spices.", "Simmer to a thick gravy.", "Serve over rice."]),
  mk("ennai-kathirikai-sadam", "Ennai Kathirikai Rice", "எண்ணெய் கத்தரிக்காய் சாதம்", ["lunch"], "main", 10,
    ["Rice", "Small brinjals", "Tamarind", "Roasted spice paste", "Sesame oil"],
    ["Stuff brinjals with spice paste.", "Cook in sesame oil with tamarind.", "Simmer till soft.", "Serve over rice."]),
  mk("arachuvitta-sambar-sadam", "Arachuvitta Sambar Rice", "அரைச்சுவிட்ட சாம்பார் சாதம்", ["lunch"], "main", 12,
    ["Rice", "Toor dal", "Fresh ground masala", "Vegetables", "Tamarind"],
    ["Grind fresh sambar masala with coconut.", "Cook dal and vegetables.", "Add tamarind and masala, simmer.", "Serve over rice."]),
  mk("rasam-sadam", "Rasam Sadam", "ரசம் சாதம்", ["lunch"], "main", 8,
    ["Rice", "Tomato", "Rasam powder", "Tamarind", "Garlic, pepper"],
    ["Make a tangy rasam with tomato and tamarind.", "Add rasam powder and crushed garlic.", "Temper and bring to a froth.", "Mix into rice."]),
  mk("paruppu-sadam", "Paruppu Sadam", "பருப்பு சாதம்", ["lunch"], "main", 13,
    ["Rice", "Toor dal", "Ghee", "Garlic, cumin", "Pepper"],
    ["Cook rice and dal soft.", "Temper garlic, cumin, pepper in ghee.", "Mash together with salt.", "Serve with ghee."]),
  mk("keerai-sadam", "Keerai Sadam", "கீரை சாதம்", ["lunch"], "main", 9,
    ["Rice", "Spinach", "Garlic", "Cumin, chilli", "Coconut"],
    ["Saute spinach with garlic and chilli.", "Grind lightly with coconut.", "Mix into rice.", "Serve warm."]),
  mk("mushroom-biryani", "Mushroom Biryani", "காளான் பிரியாணி", ["lunch"], "main", 14,
    ["Basmati rice", "Mushrooms", "Onion, tomato", "Biryani masala", "Mint, curd"],
    ["Saute mushrooms with onion and masala.", "Add curd and mint.", "Layer with par-cooked rice.", "Dum cook."]),
  mk("eral-masala-sadam", "Prawn Masala Rice", "இறால் மசாலா சாதம்", ["lunch"], "main", 26,
    ["Rice", "Prawns", "Onion, tomato", "Chilli, garam masala", "Curry leaves"],
    ["Clean and marinate prawns.", "Cook masala with onion and tomato.", "Add prawns, cook through.", "Serve with rice."]),
  mk("meen-kuzhambu-sadam", "Meen Kuzhambu Rice", "மீன் குழம்பு சாதம்", ["lunch"], "main", 25,
    ["Rice", "Fish", "Tamarind", "Chilli, coriander powder", "Sesame oil"],
    ["Make a tangy tamarind gravy.", "Slip in fish pieces.", "Simmer gently till cooked.", "Serve over rice."]),
  mk("chicken-chettinad-sadam", "Chettinad Chicken Rice", "செட்டிநாடு கோழி சாதம்", ["lunch"], "main", 32,
    ["Rice", "Chicken", "Chettinad masala", "Coconut", "Curry leaves"],
    ["Roast and grind Chettinad spices.", "Cook chicken with the masala.", "Finish with curry leaves.", "Serve with rice."]),
  mk("kola-urundai-kuzhambu", "Kola Urundai Kuzhambu", "கோலா உருண்டை குழம்பு", ["lunch"], "main", 28,
    ["Minced mutton", "Chana dal", "Onion, spices", "Tamarind gravy", "Coconut"],
    ["Make spiced mince and dal balls, steam or fry.", "Prepare a tamarind coconut gravy.", "Simmer the balls in gravy.", "Serve with rice."]),
  mk("egg-kuzhambu", "Muttai Kuzhambu", "முட்டை குழம்பு", ["lunch"], "main", 18,
    ["Boiled eggs", "Onion, tomato", "Tamarind", "Sambar powder", "Coconut paste"],
    ["Saute onion and tomato with spices.", "Add tamarind and coconut paste.", "Slip in eggs, simmer.", "Serve with rice."]),
  mk("veg-kurma-rice", "Vegetable Kurma Rice", "காய்கறி குர்மா சாதம்", ["lunch"], "main", 11,
    ["Rice", "Mixed vegetables", "Coconut, cashew paste", "Green chilli", "Garam masala"],
    ["Grind coconut and cashew paste.", "Cook vegetables with the paste.", "Simmer to a creamy kurma.", "Serve with rice."]),
  mk("paruppu-urundai-kuzhambu", "Paruppu Urundai Kuzhambu", "பருப்பு உருண்டை குழம்பு", ["lunch"], "main", 16,
    ["Toor and chana dal", "Tamarind gravy", "Sambar powder", "Coconut", "Curry leaves"],
    ["Grind soaked dal, shape balls, steam.", "Make a tamarind sambar base.", "Drop balls in, simmer.", "Serve over rice."]),
];

const LUNCH_SIDES: Dish[] = [
  mk("beans-poriyal", "Beans Poriyal", "பீன்ஸ் பொரியல்", ["lunch"], "side", 5,
    ["Chopped beans", "Coconut", "Mustard, urad dal", "Green chilli", "Curry leaves"],
    ["Temper mustard, dal, chilli.", "Add beans and a splash of water.", "Cook covered till tender.", "Add coconut, serve."]),
  mk("carrot-poriyal", "Carrot Poriyal", "கேரட் பொரியல்", ["lunch"], "side", 4,
    ["Grated carrot", "Coconut", "Mustard, urad dal", "Green chilli", "Curry leaves"],
    ["Temper mustard, dal, chilli.", "Add carrot, cook briefly.", "Add coconut.", "Serve."]),
  mk("cabbage-poriyal", "Cabbage Poriyal", "முட்டைகோஸ் பொரியல்", ["lunch"], "side", 4,
    ["Shredded cabbage", "Coconut", "Mustard, urad dal", "Green chilli", "Curry leaves"],
    ["Temper spices.", "Add cabbage, cook covered.", "Add coconut, toss.", "Serve."]),
  mk("beetroot-poriyal", "Beetroot Poriyal", "பீட்ரூட் பொரியல்", ["lunch"], "side", 4,
    ["Grated beetroot", "Coconut", "Mustard, urad dal", "Green chilli", "Curry leaves"],
    ["Temper spices.", "Add beetroot, cook covered.", "Finish with coconut.", "Serve."]),
  mk("keerai-poriyal", "Keerai Poriyal", "கீரை பொரியல்", ["lunch"], "side", 6,
    ["Spinach", "Moong dal", "Garlic", "Mustard, chilli", "Coconut"],
    ["Cook a little moong dal.", "Saute spinach with garlic.", "Combine, add coconut.", "Serve."]),
  mk("chow-chow-poriyal", "Chow Chow Poriyal", "சௌ சௌ பொரியல்", ["lunch"], "side", 4,
    ["Chayote", "Moong dal", "Coconut", "Mustard, chilli", "Curry leaves"],
    ["Cook chayote with a little dal.", "Temper and add.", "Finish with coconut.", "Serve."]),
  mk("pudalangai-poriyal", "Snake Gourd Poriyal", "புடலங்காய் பொரியல்", ["lunch"], "side", 4,
    ["Snake gourd", "Moong dal", "Coconut", "Mustard, chilli", "Curry leaves"],
    ["Cook snake gourd with dal.", "Temper spices, add.", "Finish coconut.", "Serve."]),
  mk("vendakai-poriyal", "Ladies Finger Poriyal", "வெண்டைக்காய் பொரியல்", ["lunch"], "side", 4,
    ["Okra", "Mustard, urad dal", "Onion", "Chilli powder", "Curry leaves"],
    ["Saute okra till slime goes.", "Add onion and chilli powder.", "Cook till crisp-tender.", "Serve."]),
  mk("kothavarangai-poriyal", "Cluster Beans Poriyal", "கொத்தவரங்காய் பொரியல்", ["lunch"], "side", 6,
    ["Cluster beans", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Cook cluster beans till tender.", "Temper and toss.", "Add coconut.", "Serve."]),
  mk("urulai-poriyal", "Potato Poriyal", "உருளைக்கிழங்கு பொரியல்", ["lunch"], "side", 5,
    ["Potatoes", "Mustard, urad dal", "Turmeric", "Chilli powder", "Curry leaves"],
    ["Boil and cube potatoes.", "Temper, add turmeric and chilli.", "Toss potatoes till crisp.", "Serve."]),
  mk("vazhakkai-poriyal", "Raw Banana Poriyal", "வாழைக்காய் பொரியல்", ["lunch"], "side", 5,
    ["Raw banana", "Mustard, urad dal", "Turmeric", "Chilli powder", "Curry leaves"],
    ["Boil and cube raw banana.", "Temper with turmeric and chilli.", "Toss till coated.", "Serve."]),
  mk("avarakkai-poriyal", "Broad Beans Poriyal", "அவரைக்காய் பொரியல்", ["lunch"], "side", 6,
    ["Broad beans", "Coconut", "Mustard, dal", "Green chilli", "Curry leaves"],
    ["Cook broad beans till tender.", "Temper and toss.", "Add coconut.", "Serve."]),
];

const DINNER: Dish[] = [
  mk("chapati-kurma", "Chapati with Kurma", "சப்பாத்தி குர்மா", ["dinner"], "main", 14,
    ["Wheat flour", "Mixed vegetables", "Coconut, cashew paste", "Onion, tomato", "Garam masala"],
    ["Knead and roast soft chapatis.", "Cook a creamy vegetable kurma.", "Serve hot together."]),
  mk("parotta-salna", "Parotta with Salna", "பரோட்டா சால்னா", ["dinner"], "main", 13,
    ["Maida", "Onion, tomato", "Coconut", "Spice powders", "Oil"],
    ["Make layered parottas.", "Cook a spicy salna gravy.", "Serve parotta with salna."]),
  mk("veg-kothu-parotta", "Vegetable Kothu Parotta", "காய்கறி கொத்து பரோட்டா", ["dinner"], "main", 12,
    ["Parotta", "Vegetables", "Onion, egg optional", "Salna", "Spices"],
    ["Shred parotta.", "Toss on a hot griddle with vegetables and salna.", "Chop and mix well.", "Serve hot."]),
  mk("egg-kothu-parotta", "Egg Kothu Parotta", "முட்டை கொத்து பரோட்டா", ["dinner"], "main", 20,
    ["Parotta", "Eggs", "Onion", "Salna", "Spices"],
    ["Shred parotta.", "Scramble eggs on the griddle.", "Toss with parotta and salna.", "Serve hot."]),
  mk("chicken-kothu-parotta", "Chicken Kothu Parotta", "சிக்கன் கொத்து பரோட்டா", ["dinner"], "main", 28,
    ["Parotta", "Cooked chicken", "Onion, egg", "Salna", "Spices"],
    ["Shred parotta.", "Toss with chicken, egg and salna.", "Chop together on the griddle.", "Serve hot."]),
  mk("idiyappam-kurma", "Idiyappam with Kurma", "இடியாப்பம் குர்மா", ["dinner"], "main", 10,
    ["Rice flour idiyappam", "Vegetables", "Coconut paste", "Onion, tomato", "Garam masala"],
    ["Steam fresh idiyappam.", "Cook a coconut vegetable kurma.", "Serve together."]),
  mk("poori-masala", "Poori with Potato Masala", "பூரி மசாலா", ["dinner"], "main", 10,
    ["Wheat flour", "Potatoes", "Onion", "Turmeric", "Oil"],
    ["Knead stiff dough, roll and deep fry pooris.", "Make an onion potato masala.", "Serve hot together."]),
  mk("chapati-channa", "Chapati with Channa Masala", "சப்பாத்தி சன்னா மசாலா", ["dinner"], "main", 16,
    ["Wheat flour", "Chickpeas", "Onion, tomato", "Channa masala", "Ginger garlic"],
    ["Cook chickpeas in a spiced onion tomato gravy.", "Roast soft chapatis.", "Serve together."]),
  mk("veg-fried-rice", "Vegetable Fried Rice", "காய்கறி பிரைடு ரைஸ்", ["dinner"], "main", 9,
    ["Cooked rice", "Mixed vegetables", "Soy sauce", "Garlic", "Spring onion"],
    ["Stir fry garlic and vegetables on high heat.", "Add rice and sauces.", "Toss quickly.", "Garnish spring onion."]),
  mk("gobi-fried-rice", "Gobi Fried Rice", "காலிஃபிளவர் பிரைடு ரைஸ்", ["dinner"], "main", 10,
    ["Cooked rice", "Cauliflower", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Fry cauliflower florets.", "Stir fry with rice and sauces.", "Toss on high heat.", "Serve hot."]),
  mk("egg-fried-rice", "Egg Fried Rice", "முட்டை பிரைடு ரைஸ்", ["dinner"], "main", 16,
    ["Cooked rice", "Eggs", "Soy sauce", "Garlic", "Spring onion"],
    ["Scramble eggs in hot oil.", "Add rice and soy sauce.", "Toss with garlic and spring onion.", "Serve hot."]),
  mk("chicken-fried-rice", "Chicken Fried Rice", "சிக்கன் பிரைடு ரைஸ்", ["dinner"], "main", 24,
    ["Cooked rice", "Cooked chicken", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Stir fry chicken and garlic.", "Add rice and sauces.", "Toss on high heat.", "Garnish and serve."]),
  mk("veg-noodles", "Vegetable Noodles", "காய்கறி நூடுல்ஸ்", ["dinner"], "main", 9,
    ["Noodles", "Mixed vegetables", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Boil and drain noodles.", "Stir fry vegetables and garlic.", "Toss noodles with sauces.", "Serve hot."]),
  mk("schezwan-noodles", "Schezwan Noodles", "செஸ்வான் நூடுல்ஸ்", ["dinner"], "main", 10,
    ["Noodles", "Vegetables", "Schezwan sauce", "Garlic", "Spring onion"],
    ["Boil noodles.", "Stir fry vegetables with schezwan sauce.", "Toss noodles in.", "Serve hot."]),
  mk("paneer-butter-masala", "Paneer Butter Masala with Chapati", "பன்னீர் பட்டர் மசாலா", ["dinner"], "main", 20,
    ["Paneer", "Tomato, cashew", "Butter, cream", "Garam masala", "Chapati"],
    ["Make a tomato cashew gravy with butter.", "Add paneer and cream.", "Serve with chapati."]),
  mk("mushroom-masala-chapati", "Mushroom Masala with Chapati", "காளான் மசாலா சப்பாத்தி", ["dinner"], "main", 14,
    ["Mushrooms", "Onion, tomato", "Garam masala", "Ginger garlic", "Chapati"],
    ["Saute mushrooms with onion and tomato.", "Add spices, cook to a gravy.", "Serve with chapati."]),
  mk("dal-tadka-roti", "Dal Tadka with Roti", "தால் தட்கா ரொட்டி", ["dinner"], "main", 18,
    ["Toor or moong dal", "Onion, tomato", "Garlic, cumin", "Ghee", "Roti"],
    ["Cook dal soft.", "Temper garlic, cumin, chilli in ghee.", "Add to dal.", "Serve with roti."]),
  mk("chicken-65-rice", "Chicken 65 with Rice", "சிக்கன் 65 சாதம்", ["dinner"], "main", 28,
    ["Chicken", "Curd, chilli", "Ginger garlic", "Curry leaves", "Rice"],
    ["Marinate and fry chicken.", "Toss in chilli and curry leaf tempering.", "Serve with rice or as a side."]),
  mk("chicken-gravy-idiyappam", "Chicken Gravy with Idiyappam", "சிக்கன் கிரேவி இடியாப்பம்", ["dinner"], "main", 26,
    ["Idiyappam", "Chicken", "Coconut milk", "Onion, spices", "Curry leaves"],
    ["Steam idiyappam.", "Cook chicken in a coconut milk gravy.", "Serve together."]),
  mk("mutton-sukka-dosa", "Mutton Sukka with Dosa", "மட்டன் சுக்கா தோசை", ["dinner"], "main", 30,
    ["Mutton", "Onion, spices", "Coconut", "Curry leaves", "Dosa"],
    ["Pressure cook mutton.", "Saute dry with masala and coconut.", "Serve with dosa."]),
  mk("grilled-fish-rice", "Grilled Fish with Rice", "மீன் வறுவல் சாதம்", ["dinner"], "main", 26,
    ["Fish fillets", "Chilli, turmeric", "Ginger garlic", "Lemon", "Rice"],
    ["Marinate fish in spices and lemon.", "Grill or pan sear till done.", "Serve with rice."]),
  mk("ragi-kali", "Ragi Kali with Kuzhambu", "ராகி களி", ["dinner"], "main", 9,
    ["Ragi flour", "Water", "Salt", "Spicy kuzhambu"],
    ["Cook ragi flour with water to a stiff mass.", "Shape portions.", "Serve with a spicy kuzhambu."]),
  mk("kambu-koozh", "Kambu Koozh", "கம்பு கூழ்", ["dinner"], "main", 8,
    ["Pearl millet flour", "Buttermilk", "Cooked rice", "Salt", "Small onion"],
    ["Cook millet to a porridge.", "Cool and mix with buttermilk.", "Serve with onion and pickle."]),
  mk("podi-dosa", "Podi Dosa", "பொடி தோசை", ["dinner"], "main", 8,
    ["Dosa batter", "Idli podi", "Sesame oil", "Salt"],
    ["Spread dosa on tawa.", "Sprinkle podi and oil.", "Crisp, fold and serve."]),
  mk("tomato-dosa", "Tomato Dosa", "தக்காளி தோசை", ["dinner"], "main", 7,
    ["Rice", "Tomato", "Red chilli", "Garlic", "Onion"],
    ["Grind rice with tomato, chilli, garlic.", "Spread on tawa.", "Cook crisp.", "Serve with chutney."]),
  mk("lemon-sevai", "Lemon Sevai", "எலுமிச்சை சேவை", ["dinner"], "main", 7,
    ["Rice sevai", "Lemon", "Peanuts", "Chana, urad dal", "Turmeric"],
    ["Steam or soak sevai.", "Temper dals, peanuts, turmeric.", "Toss with lemon and salt.", "Serve."]),
  mk("coconut-sevai", "Coconut Sevai", "தேங்காய் சேவை", ["dinner"], "main", 7,
    ["Rice sevai", "Coconut", "Cashews", "Chana, urad dal", "Green chilli"],
    ["Prepare sevai.", "Temper dals, cashews, chilli.", "Toss with coconut.", "Serve."]),
  mk("vegetable-uttapam", "Vegetable Uttapam", "காய்கறி ஊத்தப்பம்", ["dinner"], "main", 8,
    ["Dosa batter", "Onion, tomato, carrot", "Green chilli", "Coriander", "Oil"],
    ["Pour thick batter on tawa.", "Top with chopped vegetables.", "Cook both sides.", "Serve with chutney."]),
  mk("egg-dosa", "Egg Dosa", "முட்டை தோசை", ["dinner"], "main", 14,
    ["Dosa batter", "Eggs", "Onion, chilli", "Pepper", "Oil"],
    ["Spread dosa on tawa.", "Break an egg over and spread.", "Top with onion and pepper.", "Cook and fold."]),
  mk("keerai-masiyal-rice", "Keerai Masiyal with Rice", "கீரை மசியல் சாதம்", ["dinner"], "main", 10,
    ["Spinach", "Moong dal", "Garlic", "Cumin, chilli", "Rice"],
    ["Cook spinach with dal.", "Mash and temper with garlic and cumin.", "Serve with rice."]),
];

export const SEED_DISHES: Dish[] = [
  ...BREAKFAST,
  ...LUNCH_MAINS,
  ...LUNCH_SIDES,
  ...DINNER,
];
