import { Dish, Category, Meal } from "./types";

export function youtubeSearch(name: string): string {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(name + " recipe")}`;
}

// On-demand food-photo URL keyed by dish name. Always resolves; the UI falls
// back to an emoji tile if the image fails to load. Override per dish in the Library.
export function dishImage(name: string): string {
  const prompt = `authentic south indian tamil ${name}, plated dish, food photography, natural light, top view`;
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=600&height=400&nologo=true`;
}

function mk(
  id: string, name: string, nameTamil: string, meals: Meal[], category: Category,
  proteinGrams: number, ingredients: string[], steps: string[], pairs?: string[]
): Dish {
  return {
    id, name, nameTamil, meals, category, pairs, ingredients, steps, proteinGrams,
    youtubeUrl: youtubeSearch(name), imageUrl: dishImage(name), isCustom: false,
  };
}

// Protein values are per-serving estimates (approximate). Recipes are concise,
// best-effort guides. Verify before cooking.

const CHUTNEYS: Dish[] = [
  mk("coconut-chutney", "Coconut Chutney", "தேங்காய் சட்னி", ["breakfast", "dinner"], "chutney", 3,
    ["Grated coconut", "Roasted gram", "Green chilli", "Ginger", "Mustard, curry leaves"],
    ["Grind coconut, gram, chilli, ginger.", "Loosen with water and salt.", "Temper mustard and curry leaves.", "Mix and serve."]),
  mk("tomato-chutney", "Tomato Chutney", "தக்காளி சட்னி", ["breakfast", "dinner"], "chutney", 2,
    ["Tomatoes", "Red chilli", "Onion", "Tamarind", "Mustard, urad dal"],
    ["Saute onion, tomato, chilli, tamarind.", "Cool and grind.", "Temper mustard and dal.", "Serve."]),
  mk("mint-chutney", "Mint Chutney", "புதினா சட்னி", ["breakfast", "dinner"], "chutney", 2,
    ["Mint leaves", "Coconut", "Green chilli", "Tamarind", "Salt"],
    ["Saute mint with chilli.", "Grind with coconut and tamarind.", "Add salt.", "Serve."]),
  mk("peanut-chutney", "Peanut Chutney", "வேர்க்கடலை சட்னி", ["breakfast", "dinner"], "chutney", 6,
    ["Roasted peanuts", "Red chilli", "Garlic", "Tamarind", "Mustard"],
    ["Grind peanuts, chilli, garlic, tamarind.", "Loosen with water and salt.", "Temper mustard.", "Serve."]),
  mk("onion-chutney", "Onion Chutney", "வெங்காய சட்னி", ["breakfast", "dinner"], "chutney", 2,
    ["Small onions", "Red chilli", "Tamarind", "Urad dal", "Oil"],
    ["Saute onions, chilli, dal, tamarind.", "Cool and grind.", "Temper.", "Serve."]),
  mk("coriander-chutney", "Coriander Chutney", "கொத்தமல்லி சட்னி", ["breakfast", "dinner"], "chutney", 2,
    ["Coriander leaves", "Coconut", "Green chilli", "Tamarind", "Salt"],
    ["Saute coriander and chilli.", "Grind with coconut and tamarind.", "Add salt.", "Serve."]),
];

const SAMBARS: Dish[] = [
  mk("tiffin-sambar", "Tiffin Sambar", "டிஃபன் சாம்பார்", ["breakfast", "dinner"], "sambar", 8,
    ["Toor dal", "Small onions", "Tomato", "Sambar powder", "Tamarind"],
    ["Cook toor dal soft.", "Saute onion and tomato.", "Add tamarind, sambar powder, dal.", "Simmer, temper and serve."]),
  mk("drumstick-sambar", "Drumstick Sambar", "முருங்கைக்காய் சாம்பார்", ["breakfast", "dinner"], "sambar", 8,
    ["Toor dal", "Drumstick", "Tomato", "Sambar powder", "Tamarind"],
    ["Cook dal and drumstick.", "Add tamarind and sambar powder.", "Simmer to blend.", "Temper and serve."]),
];

const RICE: Dish[] = [
  mk("steamed-rice", "Steamed Rice", "சாதம்", ["lunch"], "rice", 4,
    ["Raw rice", "Water", "Salt"],
    ["Rinse rice.", "Cook with water till soft.", "Fluff and serve as the thali base."]),
  mk("ghee-rice", "Ghee Rice", "நெய் சாதம்", ["lunch"], "rice", 5,
    ["Basmati rice", "Ghee", "Whole spices", "Onion", "Salt"],
    ["Saute spices and onion in ghee.", "Add rice and water.", "Cook till fluffy.", "Serve as the base."]),
];

const RASAMS: Dish[] = [
  mk("tomato-rasam", "Tomato Rasam", "தக்காளி ரசம்", ["lunch"], "rasam", 3,
    ["Tomato", "Tamarind", "Rasam powder", "Garlic", "Coriander"],
    ["Simmer tomato, tamarind, rasam powder.", "Add crushed garlic.", "Temper and froth.", "Serve."]),
  mk("pepper-rasam", "Pepper Rasam", "மிளகு ரசம்", ["lunch"], "rasam", 3,
    ["Pepper, cumin", "Tamarind", "Garlic", "Tomato", "Curry leaves"],
    ["Crush pepper and cumin.", "Simmer with tamarind and tomato.", "Temper and froth.", "Serve."]),
  mk("garlic-rasam", "Garlic Rasam", "பூண்டு ரசம்", ["lunch"], "rasam", 3,
    ["Garlic", "Tamarind", "Rasam powder", "Tomato", "Curry leaves"],
    ["Crush plenty of garlic.", "Simmer with tamarind and rasam powder.", "Temper and froth.", "Serve."]),
  mk("lemon-rasam", "Lemon Rasam", "எலுமிச்சை ரசம்", ["lunch"], "rasam", 3,
    ["Toor dal water", "Lemon", "Green chilli", "Ginger", "Coriander"],
    ["Heat dal water with chilli and ginger.", "Froth and switch off.", "Add lemon juice.", "Serve."]),
];

const CURDS: Dish[] = [
  mk("curd", "Curd", "தயிர்", ["lunch", "dinner"], "curd", 4,
    ["Fresh curd", "Salt"],
    ["Whisk fresh curd smooth.", "Add a little salt.", "Serve chilled."]),
  mk("onion-raita", "Onion Raita", "வெங்காய ரைதா", ["lunch", "dinner"], "curd", 4,
    ["Curd", "Onion", "Green chilli", "Coriander", "Salt"],
    ["Whisk curd.", "Mix in chopped onion, chilli, coriander.", "Add salt.", "Serve chilled."]),
  mk("cucumber-raita", "Cucumber Raita", "வெள்ளரிக்காய் ரைதா", ["lunch", "dinner"], "curd", 4,
    ["Curd", "Cucumber", "Green chilli", "Coriander", "Salt"],
    ["Whisk curd.", "Grate in cucumber.", "Add chilli, coriander, salt.", "Serve chilled."]),
];

const BREAKFAST: Dish[] = [
  mk("idli", "Idli", "இட்லி", ["breakfast", "dinner"], "tiffin", 6,
    ["Idli rice", "Urad dal", "Fenugreek", "Salt"],
    ["Soak, grind and ferment the batter.", "Pour into moulds.", "Steam 10 to 12 minutes.", "Serve."],
    ["tiffin-sambar", "coconut-chutney"]),
  mk("plain-dosa", "Plain Dosa", "தோசை", ["breakfast", "dinner"], "tiffin", 7,
    ["Dosa rice", "Urad dal", "Fenugreek", "Salt", "Oil"],
    ["Ferment the batter.", "Spread thin on a hot tawa.", "Drizzle oil, cook crisp.", "Serve."],
    ["coconut-chutney", "tiffin-sambar"]),
  mk("masala-dosa", "Masala Dosa", "மசாலா தோசை", ["breakfast"], "tiffin", 9,
    ["Dosa batter", "Potato", "Onion", "Turmeric", "Mustard"],
    ["Make potato masala.", "Crisp a dosa.", "Fill and fold.", "Serve."],
    ["coconut-chutney"]),
  mk("rava-dosa", "Rava Dosa", "ரவா தோசை", ["breakfast"], "tiffin", 6,
    ["Rava", "Rice flour", "Cumin, chilli", "Onion", "Salt"],
    ["Mix a thin batter, rest.", "Sprinkle on hot tawa.", "Crisp with oil.", "Serve."],
    ["coconut-chutney"]),
  mk("ven-pongal", "Ven Pongal", "வெண் பொங்கல்", ["breakfast"], "tiffin", 9,
    ["Rice", "Moong dal", "Pepper, cumin", "Ginger, cashews", "Ghee"],
    ["Cook rice and dal soft.", "Temper pepper, cumin, cashews in ghee.", "Mix in.", "Serve hot."],
    ["coconut-chutney", "tiffin-sambar"]),
  mk("sakkarai-pongal", "Sakkarai Pongal", "சக்கரை பொங்கல்", ["breakfast"], "tiffin", 7,
    ["Rice", "Moong dal", "Jaggery", "Ghee, cashews", "Cardamom"],
    ["Cook rice and dal.", "Melt jaggery, mix in.", "Add ghee cashews, cardamom.", "Serve."]),
  mk("idiyappam", "Idiyappam", "இடியாப்பம்", ["breakfast", "dinner"], "tiffin", 6,
    ["Rice flour", "Hot water", "Salt", "Oil"],
    ["Make soft dough.", "Press through mould.", "Steam 6 to 8 minutes.", "Serve."],
    ["coconut-chutney"]),
  mk("aappam", "Aappam", "ஆப்பம்", ["breakfast"], "tiffin", 6,
    ["Raw rice", "Coconut", "Yeast", "Salt"],
    ["Grind and ferment.", "Swirl in an appam pan.", "Cover and cook.", "Serve."],
    ["coconut-chutney"]),
  mk("uttapam", "Uttapam", "ஊத்தப்பம்", ["breakfast"], "tiffin", 7,
    ["Dosa batter", "Onion, tomato", "Chilli", "Coriander", "Oil"],
    ["Pour thick batter.", "Top with vegetables.", "Cook both sides.", "Serve."],
    ["coconut-chutney"]),
  mk("onion-uttapam", "Onion Uttapam", "வெங்காய ஊத்தப்பம்", ["breakfast"], "tiffin", 7,
    ["Dosa batter", "Onion", "Chilli", "Curry leaves", "Oil"],
    ["Spread thick batter.", "Press on onion and chilli.", "Cook golden.", "Serve."],
    ["coconut-chutney"]),
  mk("pesarattu", "Pesarattu", "பெசரட்டு", ["breakfast"], "tiffin", 14,
    ["Green gram", "Chilli", "Ginger", "Salt", "Oil"],
    ["Soak and grind green gram.", "Spread thin.", "Crisp with oil.", "Serve."],
    ["coconut-chutney"]),
  mk("adai", "Adai", "அடை", ["breakfast"], "tiffin", 15,
    ["Mixed dals", "Rice", "Red chilli", "Asafoetida", "Curry leaves"],
    ["Coarse grind dals and rice.", "Spread thick.", "Cook crisp.", "Serve."],
    ["coconut-chutney"]),
  mk("rava-upma", "Rava Upma", "ரவா உப்புமா", ["breakfast"], "tiffin", 6,
    ["Rava", "Onion, chilli", "Mustard, urad dal", "Curry leaves", "Water"],
    ["Roast rava.", "Temper and saute onion.", "Add water and rava.", "Cook fluffy."],
    ["coconut-chutney"]),
  mk("semiya-upma", "Semiya Upma", "செமியா உப்புமா", ["breakfast"], "tiffin", 6,
    ["Vermicelli", "Vegetables", "Mustard, dal", "Curry leaves", "Water"],
    ["Roast vermicelli.", "Saute vegetables.", "Cook with water.", "Serve."]),
  mk("arisi-upma", "Arisi Upma", "அரிசி உப்புமா", ["breakfast"], "tiffin", 7,
    ["Raw rice", "Toor dal", "Pepper, cumin", "Coconut", "Curry leaves"],
    ["Coarse grind rice with spices.", "Roast with dal.", "Cook with water.", "Serve."]),
  mk("aval-upma", "Aval Upma", "அவல் உப்புமா", ["breakfast"], "tiffin", 5,
    ["Poha", "Onion, chilli", "Mustard, peanuts", "Turmeric", "Curry leaves"],
    ["Rinse poha.", "Temper and saute.", "Mix poha and warm.", "Serve."]),
  mk("kuzhi-paniyaram", "Kuzhi Paniyaram", "குழி பணியாரம்", ["breakfast"], "tiffin", 7,
    ["Dosa batter", "Onion, chilli", "Mustard", "Curry leaves", "Oil"],
    ["Mix tempered onion into batter.", "Pour into paniyaram pan.", "Flip till golden.", "Serve."],
    ["coconut-chutney"]),
  mk("medhu-vada", "Medhu Vada", "மெது வடை", ["breakfast"], "tiffin", 11,
    ["Urad dal", "Pepper, cumin", "Onion", "Salt", "Oil"],
    ["Grind dal fluffy.", "Add pepper, cumin, onion.", "Shape and deep fry.", "Serve."],
    ["coconut-chutney", "tiffin-sambar"]),
  mk("ragi-dosa", "Ragi Dosa", "ராகி தோசை", ["breakfast"], "tiffin", 7,
    ["Ragi flour", "Rice flour", "Onion, chilli", "Cumin", "Salt"],
    ["Mix thin batter.", "Spread on tawa.", "Crisp with oil.", "Serve."],
    ["coconut-chutney"]),
  mk("set-dosa", "Set Dosa", "செட் தோசை", ["breakfast"], "tiffin", 7,
    ["Dosa batter", "Curd", "Soda", "Salt", "Oil"],
    ["Loosen batter with curd.", "Pour thick rounds.", "Cook soft and spongy.", "Serve."],
    ["coconut-chutney"]),
  mk("godhumai-dosa", "Wheat Dosa", "கோதுமை தோசை", ["breakfast"], "tiffin", 8,
    ["Wheat flour", "Onion, chilli", "Cumin", "Curry leaves", "Salt"],
    ["Whisk thin batter.", "Pour from edges.", "Crisp it.", "Serve."],
    ["coconut-chutney"]),
  mk("kambu-dosa", "Kambu Dosa", "கம்பு தோசை", ["breakfast"], "tiffin", 9,
    ["Pearl millet flour", "Rice", "Urad dal", "Salt", "Oil"],
    ["Grind and ferment.", "Spread on tawa.", "Cook crisp.", "Serve."],
    ["coconut-chutney"]),
  mk("thinai-pongal", "Thinai Pongal", "தினை பொங்கல்", ["breakfast"], "tiffin", 8,
    ["Foxtail millet", "Moong dal", "Pepper, cumin", "Cashews", "Ghee"],
    ["Cook millet and dal.", "Temper spices in ghee.", "Mix in.", "Serve."],
    ["coconut-chutney"]),
  mk("semiya-idli", "Semiya Idli", "செமியா இட்லி", ["breakfast"], "tiffin", 6,
    ["Vermicelli", "Rava", "Curd", "Carrot", "Eno"],
    ["Mix vermicelli, rava, curd, vegetables.", "Add eno.", "Steam 10 minutes.", "Serve."],
    ["coconut-chutney"]),
  mk("rava-idli", "Rava Idli", "ரவா இட்லி", ["breakfast"], "tiffin", 6,
    ["Rava", "Curd", "Cashews", "Mustard", "Eno"],
    ["Mix rava and curd.", "Temper and add.", "Add eno, steam.", "Serve."],
    ["coconut-chutney"]),
  mk("kara-dosa", "Kara Dosa", "கார தோசை", ["breakfast"], "tiffin", 7,
    ["Dosa batter", "Onion", "Chilli paste", "Curry leaves", "Oil"],
    ["Spread dosa, smear chilli paste.", "Top onion and curry leaves.", "Crisp it.", "Serve."],
    ["coconut-chutney"]),
  mk("podi-idli", "Podi Idli", "பொடி இட்லி", ["breakfast"], "tiffin", 7,
    ["Mini idlis", "Idli podi", "Sesame oil", "Mustard", "Curry leaves"],
    ["Steam mini idlis.", "Temper mustard.", "Toss with podi and oil.", "Serve."],
    ["coconut-chutney"]),
  mk("ghee-roast-dosa", "Ghee Roast Dosa", "நெய் ரோஸ்ட் தோசை", ["breakfast"], "tiffin", 8,
    ["Dosa batter", "Ghee", "Idli podi", "Salt"],
    ["Spread very thin.", "Drizzle ghee.", "Sprinkle podi, roast crisp.", "Serve."],
    ["coconut-chutney"]),
  mk("rava-kichadi", "Rava Kichadi", "ரவா கிச்சடி", ["breakfast"], "tiffin", 7,
    ["Rava", "Vegetables", "Onion, tomato", "Ginger, chilli", "Ghee"],
    ["Roast rava.", "Saute vegetables.", "Cook soft with water.", "Finish ghee, serve."],
    ["coconut-chutney"]),
  mk("paniyaram-sweet", "Sweet Paniyaram", "இனிப்பு பணியாரம்", ["breakfast"], "tiffin", 6,
    ["Rice flour", "Jaggery", "Banana", "Cardamom", "Oil"],
    ["Mix rice flour, jaggery, banana.", "Pour into paniyaram pan.", "Cook till golden.", "Serve."]),
];

const KUZHAMBU: Dish[] = [
  mk("lunch-sambar", "Sambar", "சாம்பார்", ["lunch"], "kuzhambu", 9,
    ["Toor dal", "Vegetables", "Sambar powder", "Tamarind", "Tempering"],
    ["Cook dal and vegetables.", "Add tamarind and sambar powder.", "Simmer and temper.", "Serve over rice."]),
  mk("vatha-kuzhambu", "Vatha Kuzhambu", "வத்தக் குழம்பு", ["lunch"], "kuzhambu", 8,
    ["Tamarind", "Sundakkai vathal", "Sambar powder", "Small onions", "Sesame oil"],
    ["Fry vathal and onions.", "Add tamarind and spices.", "Simmer thick.", "Serve over rice."]),
  mk("kara-kuzhambu", "Kara Kuzhambu", "கார குழம்பு", ["lunch"], "kuzhambu", 9,
    ["Tamarind", "Small onions", "Brinjal", "Sambar powder", "Sesame oil"],
    ["Saute onion and brinjal.", "Add tamarind and spices.", "Simmer spicy.", "Serve over rice."]),
  mk("mor-kuzhambu", "Mor Kuzhambu", "மோர் குழம்பு", ["lunch"], "kuzhambu", 8,
    ["Buttermilk", "Coconut, cumin", "Ash gourd", "Green chilli", "Curry leaves"],
    ["Grind coconut and cumin.", "Cook vegetable, add buttermilk.", "Warm gently.", "Serve over rice."]),
  mk("milagu-kuzhambu", "Milagu Kuzhambu", "மிளகு குழம்பு", ["lunch"], "kuzhambu", 9,
    ["Pepper", "Tamarind", "Toor dal", "Garlic", "Sesame oil"],
    ["Roast and grind pepper.", "Cook with tamarind.", "Simmer peppery.", "Serve over rice."]),
  mk("poondu-kuzhambu", "Poondu Kuzhambu", "பூண்டு குழம்பு", ["lunch"], "kuzhambu", 9,
    ["Garlic", "Tamarind", "Sambar powder", "Small onions", "Sesame oil"],
    ["Fry garlic in sesame oil.", "Add tamarind and spices.", "Simmer thick.", "Serve over rice."]),
  mk("vendhaya-kuzhambu", "Vendhaya Kuzhambu", "வெந்தயக் குழம்பு", ["lunch"], "kuzhambu", 9,
    ["Fenugreek", "Tamarind", "Sambar powder", "Garlic", "Sesame oil"],
    ["Roast and grind fenugreek.", "Cook tamarind base.", "Simmer thick.", "Serve over rice."]),
  mk("ennai-kathirikai", "Ennai Kathirikai", "எண்ணெய் கத்தரிக்காய்", ["lunch"], "kuzhambu", 9,
    ["Small brinjals", "Spice paste", "Tamarind", "Sesame oil", "Curry leaves"],
    ["Stuff brinjals with paste.", "Cook in sesame oil and tamarind.", "Simmer soft.", "Serve over rice."]),
  mk("meen-kuzhambu", "Meen Kuzhambu", "மீன் குழம்பு", ["lunch"], "kuzhambu", 24,
    ["Fish", "Tamarind", "Chilli, coriander powder", "Small onions", "Sesame oil"],
    ["Make a tangy tamarind gravy.", "Slip in fish.", "Simmer gently.", "Serve over rice."]),
  mk("egg-kuzhambu", "Muttai Kuzhambu", "முட்டை குழம்பு", ["lunch"], "kuzhambu", 16,
    ["Boiled eggs", "Onion, tomato", "Tamarind", "Sambar powder", "Coconut paste"],
    ["Saute onion and tomato.", "Add tamarind and coconut.", "Add eggs, simmer.", "Serve over rice."]),
  mk("kola-urundai-kuzhambu", "Kola Urundai Kuzhambu", "கோலா உருண்டை குழம்பு", ["lunch"], "kuzhambu", 22,
    ["Minced mutton", "Chana dal", "Spices", "Tamarind gravy", "Coconut"],
    ["Make spiced mince balls, steam.", "Prepare coconut tamarind gravy.", "Simmer balls in gravy.", "Serve over rice."]),
  mk("paruppu-urundai-kuzhambu", "Paruppu Urundai Kuzhambu", "பருப்பு உருண்டை குழம்பு", ["lunch"], "kuzhambu", 14,
    ["Toor and chana dal", "Tamarind gravy", "Sambar powder", "Coconut", "Curry leaves"],
    ["Grind dal, shape balls, steam.", "Make tamarind base.", "Simmer balls in.", "Serve over rice."]),
  mk("veg-kurma", "Vegetable Kurma", "காய்கறி குர்மா", ["lunch"], "kuzhambu", 10,
    ["Mixed vegetables", "Coconut, cashew paste", "Green chilli", "Onion", "Garam masala"],
    ["Grind coconut cashew paste.", "Cook vegetables with paste.", "Simmer creamy.", "Serve with rice."]),
];

const LUNCH_ONEPOT: Dish[] = [
  mk("sambar-sadam", "Sambar Sadam", "சாம்பார் சாதம்", ["lunch"], "onepot", 12,
    ["Rice", "Toor dal", "Vegetables", "Sambar powder", "Tamarind"],
    ["Pressure cook rice, dal, vegetables.", "Add tamarind and sambar powder.", "Temper and mix.", "Serve."]),
  mk("thayir-sadam", "Thayir Sadam", "தயிர் சாதம்", ["lunch"], "onepot", 9,
    ["Cooked rice", "Curd", "Milk", "Ginger, chilli", "Mustard"],
    ["Mash rice, mix curd and milk.", "Temper and add.", "Season.", "Serve chilled."]),
  mk("lemon-rice", "Lemon Rice", "எலுமிச்சை சாதம்", ["lunch"], "onepot", 7,
    ["Cooked rice", "Lemon", "Peanuts", "Dals", "Turmeric"],
    ["Temper dals, peanuts, turmeric.", "Add to rice.", "Squeeze lemon, mix.", "Serve."]),
  mk("tomato-rice", "Tomato Rice", "தக்காளி சாதம்", ["lunch"], "onepot", 8,
    ["Cooked rice", "Tomato", "Onion", "Chilli powder", "Garam masala"],
    ["Cook onion tomato masala.", "Add spices.", "Mix in rice.", "Serve."]),
  mk("coconut-rice", "Coconut Rice", "தேங்காய் சாதம்", ["lunch"], "onepot", 8,
    ["Cooked rice", "Coconut", "Cashews", "Dals", "Chilli"],
    ["Temper dals, cashews, chilli.", "Add coconut.", "Mix in rice.", "Serve."]),
  mk("puliyodarai", "Puliyodarai", "புளியோதரை", ["lunch"], "onepot", 8,
    ["Cooked rice", "Tamarind", "Peanuts", "Sesame, chilli", "Puli spices"],
    ["Make tangy tamarind paste.", "Roast peanuts and sesame.", "Mix into rice.", "Rest and serve."]),
  mk("karuveppilai-sadam", "Curry Leaf Rice", "கருவேப்பிலை சாதம்", ["lunch"], "onepot", 8,
    ["Cooked rice", "Curry leaves", "Dals", "Chilli", "Coconut"],
    ["Roast and grind a podi.", "Mix into rice with oil.", "Serve."]),
  mk("veg-biryani", "Vegetable Biryani", "காய்கறி பிரியாணி", ["lunch"], "onepot", 12,
    ["Basmati rice", "Vegetables", "Onion, tomato", "Biryani masala", "Mint, curd"],
    ["Saute vegetables with masala.", "Add curd and mint.", "Layer with rice.", "Dum cook."]),
  mk("chicken-biryani", "Chicken Biryani", "சிக்கன் பிரியாணி", ["lunch"], "onepot", 30,
    ["Basmati rice", "Chicken", "Onion, tomato", "Biryani masala", "Curd, mint"],
    ["Marinate chicken.", "Build masala.", "Layer with rice.", "Dum cook."]),
  mk("mutton-biryani", "Mutton Biryani", "மட்டன் பிரியாணி", ["lunch"], "onepot", 33,
    ["Seeraga samba rice", "Mutton", "Onion, tomato", "Biryani masala", "Curd, mint"],
    ["Cook mutton with spices.", "Build masala.", "Layer with rice.", "Dum cook."]),
  mk("egg-biryani", "Egg Biryani", "முட்டை பிரியாணி", ["lunch"], "onepot", 18,
    ["Basmati rice", "Boiled eggs", "Onion, tomato", "Biryani masala", "Mint"],
    ["Make masala base.", "Layer rice and eggs.", "Dum cook.", "Serve."]),
  mk("mushroom-biryani", "Mushroom Biryani", "காளான் பிரியாணி", ["lunch"], "onepot", 14,
    ["Basmati rice", "Mushrooms", "Onion, tomato", "Biryani masala", "Mint"],
    ["Saute mushrooms with masala.", "Add curd and mint.", "Layer with rice.", "Dum cook."]),
  mk("rasam-sadam", "Rasam Sadam", "ரசம் சாதம்", ["lunch"], "onepot", 8,
    ["Rice", "Tomato", "Rasam powder", "Tamarind", "Garlic"],
    ["Make tangy rasam.", "Temper and froth.", "Mix into rice.", "Serve."]),
  mk("paruppu-sadam", "Paruppu Sadam", "பருப்பு சாதம்", ["lunch"], "onepot", 13,
    ["Rice", "Toor dal", "Ghee", "Garlic, cumin", "Pepper"],
    ["Cook rice and dal soft.", "Temper in ghee.", "Mash with salt.", "Serve."]),
  mk("keerai-sadam", "Keerai Sadam", "கீரை சாதம்", ["lunch"], "onepot", 9,
    ["Rice", "Spinach", "Garlic", "Cumin, chilli", "Coconut"],
    ["Saute spinach with garlic.", "Grind with coconut.", "Mix into rice.", "Serve."]),
  mk("eral-masala-sadam", "Prawn Masala Rice", "இறால் மசாலா சாதம்", ["lunch"], "onepot", 26,
    ["Rice", "Prawns", "Onion, tomato", "Chilli, garam masala", "Curry leaves"],
    ["Cook prawn masala.", "Mix with rice.", "Garnish.", "Serve."]),
  mk("chettinad-chicken-rice", "Chettinad Chicken Rice", "செட்டிநாடு கோழி சாதம்", ["lunch"], "onepot", 32,
    ["Rice", "Chicken", "Chettinad masala", "Coconut", "Curry leaves"],
    ["Roast and grind spices.", "Cook chicken in masala.", "Serve with rice."]),
];

const POROYAL: Dish[] = [
  mk("beans-poriyal", "Beans Poriyal", "பீன்ஸ் பொரியல்", ["lunch"], "poriyal", 5,
    ["Beans", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Temper spices.", "Cook beans tender.", "Add coconut.", "Serve."]),
  mk("carrot-poriyal", "Carrot Poriyal", "கேரட் பொரியல்", ["lunch"], "poriyal", 4,
    ["Carrot", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Temper spices.", "Cook carrot.", "Add coconut.", "Serve."]),
  mk("cabbage-poriyal", "Cabbage Poriyal", "முட்டைகோஸ் பொரியல்", ["lunch"], "poriyal", 4,
    ["Cabbage", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Temper.", "Cook cabbage.", "Add coconut.", "Serve."]),
  mk("beetroot-poriyal", "Beetroot Poriyal", "பீட்ரூட் பொரியல்", ["lunch"], "poriyal", 4,
    ["Beetroot", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Temper.", "Cook beetroot.", "Add coconut.", "Serve."]),
  mk("keerai-poriyal", "Keerai Poriyal", "கீரை பொரியல்", ["lunch"], "poriyal", 6,
    ["Spinach", "Moong dal", "Garlic", "Chilli", "Coconut"],
    ["Cook a little dal.", "Saute spinach.", "Combine, add coconut.", "Serve."]),
  mk("chow-chow-poriyal", "Chow Chow Poriyal", "சௌ சௌ பொரியல்", ["lunch"], "poriyal", 4,
    ["Chayote", "Moong dal", "Coconut", "Chilli", "Curry leaves"],
    ["Cook chayote with dal.", "Temper.", "Add coconut.", "Serve."]),
  mk("pudalangai-poriyal", "Snake Gourd Poriyal", "புடலங்காய் பொரியல்", ["lunch"], "poriyal", 4,
    ["Snake gourd", "Moong dal", "Coconut", "Chilli", "Curry leaves"],
    ["Cook with dal.", "Temper.", "Add coconut.", "Serve."]),
  mk("vendakai-poriyal", "Ladies Finger Poriyal", "வெண்டைக்காய் பொரியல்", ["lunch"], "poriyal", 4,
    ["Okra", "Mustard, dal", "Onion", "Chilli powder", "Curry leaves"],
    ["Saute okra.", "Add onion and chilli.", "Cook crisp.", "Serve."]),
  mk("kothavarangai-poriyal", "Cluster Beans Poriyal", "கொத்தவரங்காய் பொரியல்", ["lunch"], "poriyal", 6,
    ["Cluster beans", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Cook beans tender.", "Temper.", "Add coconut.", "Serve."]),
  mk("urulai-poriyal", "Potato Poriyal", "உருளைக்கிழங்கு பொரியல்", ["lunch"], "poriyal", 5,
    ["Potato", "Mustard, dal", "Turmeric", "Chilli powder", "Curry leaves"],
    ["Boil and cube potato.", "Temper and toss.", "Crisp it.", "Serve."]),
  mk("vazhakkai-poriyal", "Raw Banana Poriyal", "வாழைக்காய் பொரியல்", ["lunch"], "poriyal", 5,
    ["Raw banana", "Mustard, dal", "Turmeric", "Chilli powder", "Curry leaves"],
    ["Boil and cube.", "Temper and toss.", "Coat well.", "Serve."]),
  mk("avarakkai-poriyal", "Broad Beans Poriyal", "அவரைக்காய் பொரியல்", ["lunch"], "poriyal", 6,
    ["Broad beans", "Coconut", "Mustard, dal", "Chilli", "Curry leaves"],
    ["Cook tender.", "Temper.", "Add coconut.", "Serve."]),
];

const DINNER_TIFFIN: Dish[] = [
  mk("podi-dosa", "Podi Dosa", "பொடி தோசை", ["dinner"], "tiffin", 8,
    ["Dosa batter", "Idli podi", "Sesame oil", "Salt"],
    ["Spread dosa.", "Sprinkle podi and oil.", "Crisp, fold, serve."],
    ["coconut-chutney"]),
  mk("tomato-dosa", "Tomato Dosa", "தக்காளி தோசை", ["dinner"], "tiffin", 7,
    ["Rice", "Tomato", "Chilli", "Garlic", "Onion"],
    ["Grind rice with tomato.", "Spread on tawa.", "Cook crisp.", "Serve."],
    ["coconut-chutney"]),
  mk("egg-dosa", "Egg Dosa", "முட்டை தோசை", ["dinner"], "tiffin", 14,
    ["Dosa batter", "Eggs", "Onion, chilli", "Pepper", "Oil"],
    ["Spread dosa.", "Break egg over and spread.", "Top onion and pepper.", "Fold and serve."],
    ["coconut-chutney"]),
  mk("vegetable-uttapam", "Vegetable Uttapam", "காய்கறி ஊத்தப்பம்", ["dinner"], "tiffin", 8,
    ["Dosa batter", "Onion, tomato, carrot", "Chilli", "Coriander", "Oil"],
    ["Pour thick batter.", "Top with vegetables.", "Cook both sides.", "Serve."],
    ["coconut-chutney"]),
];

const DINNER_ONEPOT: Dish[] = [
  mk("chapati-kurma", "Chapati with Kurma", "சப்பாத்தி குர்மா", ["dinner"], "onepot", 14,
    ["Wheat flour", "Vegetables", "Coconut cashew paste", "Onion, tomato", "Garam masala"],
    ["Roast soft chapatis.", "Cook a creamy kurma.", "Serve together."]),
  mk("parotta-salna", "Parotta with Salna", "பரோட்டா சால்னா", ["dinner"], "onepot", 13,
    ["Maida", "Onion, tomato", "Coconut", "Spice powders", "Oil"],
    ["Make layered parottas.", "Cook a spicy salna.", "Serve together."]),
  mk("veg-kothu-parotta", "Vegetable Kothu Parotta", "காய்கறி கொத்து பரோட்டா", ["dinner"], "onepot", 12,
    ["Parotta", "Vegetables", "Onion", "Salna", "Spices"],
    ["Shred parotta.", "Toss with vegetables and salna.", "Chop and mix.", "Serve."]),
  mk("egg-kothu-parotta", "Egg Kothu Parotta", "முட்டை கொத்து பரோட்டா", ["dinner"], "onepot", 20,
    ["Parotta", "Eggs", "Onion", "Salna", "Spices"],
    ["Shred parotta.", "Scramble eggs.", "Toss with salna.", "Serve."]),
  mk("chicken-kothu-parotta", "Chicken Kothu Parotta", "சிக்கன் கொத்து பரோட்டா", ["dinner"], "onepot", 28,
    ["Parotta", "Chicken", "Onion, egg", "Salna", "Spices"],
    ["Shred parotta.", "Toss with chicken and salna.", "Chop together.", "Serve."]),
  mk("idiyappam-kurma", "Idiyappam with Kurma", "இடியாப்பம் குர்மா", ["dinner"], "onepot", 10,
    ["Idiyappam", "Vegetables", "Coconut paste", "Onion, tomato", "Garam masala"],
    ["Steam idiyappam.", "Cook a coconut kurma.", "Serve together."]),
  mk("poori-masala", "Poori with Masala", "பூரி மசாலா", ["dinner"], "onepot", 10,
    ["Wheat flour", "Potato", "Onion", "Turmeric", "Oil"],
    ["Roll and fry pooris.", "Make onion potato masala.", "Serve together."]),
  mk("chapati-channa", "Chapati with Channa", "சப்பாத்தி சன்னா", ["dinner"], "onepot", 16,
    ["Wheat flour", "Chickpeas", "Onion, tomato", "Channa masala", "Ginger garlic"],
    ["Cook chickpea gravy.", "Roast chapatis.", "Serve together."]),
  mk("veg-fried-rice", "Vegetable Fried Rice", "காய்கறி பிரைடு ரைஸ்", ["dinner"], "onepot", 9,
    ["Cooked rice", "Vegetables", "Soy sauce", "Garlic", "Spring onion"],
    ["Stir fry garlic and vegetables.", "Add rice and sauce.", "Toss high heat.", "Serve."]),
  mk("gobi-fried-rice", "Gobi Fried Rice", "காலிஃபிளவர் பிரைடு ரைஸ்", ["dinner"], "onepot", 10,
    ["Cooked rice", "Cauliflower", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Fry cauliflower.", "Stir fry with rice.", "Toss.", "Serve."]),
  mk("egg-fried-rice", "Egg Fried Rice", "முட்டை பிரைடு ரைஸ்", ["dinner"], "onepot", 16,
    ["Cooked rice", "Eggs", "Soy sauce", "Garlic", "Spring onion"],
    ["Scramble eggs.", "Add rice and soy.", "Toss.", "Serve."]),
  mk("chicken-fried-rice", "Chicken Fried Rice", "சிக்கன் பிரைடு ரைஸ்", ["dinner"], "onepot", 24,
    ["Cooked rice", "Chicken", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Stir fry chicken and garlic.", "Add rice and sauce.", "Toss.", "Serve."]),
  mk("veg-noodles", "Vegetable Noodles", "காய்கறி நூடுல்ஸ்", ["dinner"], "onepot", 9,
    ["Noodles", "Vegetables", "Soy, chilli sauce", "Garlic", "Spring onion"],
    ["Boil noodles.", "Stir fry vegetables.", "Toss with sauce.", "Serve."]),
  mk("schezwan-noodles", "Schezwan Noodles", "செஸ்வான் நூடுல்ஸ்", ["dinner"], "onepot", 10,
    ["Noodles", "Vegetables", "Schezwan sauce", "Garlic", "Spring onion"],
    ["Boil noodles.", "Stir fry with schezwan sauce.", "Toss.", "Serve."]),
  mk("paneer-butter-masala", "Paneer Butter Masala", "பன்னீர் பட்டர் மசாலா", ["dinner"], "onepot", 20,
    ["Paneer", "Tomato, cashew", "Butter, cream", "Garam masala", "Chapati"],
    ["Make tomato cashew gravy.", "Add paneer and cream.", "Serve with chapati."]),
  mk("mushroom-masala-chapati", "Mushroom Masala with Chapati", "காளான் மசாலா", ["dinner"], "onepot", 14,
    ["Mushrooms", "Onion, tomato", "Garam masala", "Ginger garlic", "Chapati"],
    ["Saute mushrooms.", "Cook to a gravy.", "Serve with chapati."]),
  mk("dal-tadka-roti", "Dal Tadka with Roti", "தால் தட்கா ரொட்டி", ["dinner"], "onepot", 18,
    ["Dal", "Onion, tomato", "Garlic, cumin", "Ghee", "Roti"],
    ["Cook dal soft.", "Temper in ghee.", "Serve with roti."]),
  mk("chicken-65-rice", "Chicken 65 with Rice", "சிக்கன் 65 சாதம்", ["dinner"], "onepot", 28,
    ["Chicken", "Curd, chilli", "Ginger garlic", "Curry leaves", "Rice"],
    ["Marinate and fry chicken.", "Toss in tempering.", "Serve with rice."]),
  mk("chicken-gravy-idiyappam", "Chicken Gravy with Idiyappam", "சிக்கன் கிரேவி இடியாப்பம்", ["dinner"], "onepot", 26,
    ["Idiyappam", "Chicken", "Coconut milk", "Onion, spices", "Curry leaves"],
    ["Steam idiyappam.", "Cook chicken in coconut gravy.", "Serve together."]),
  mk("mutton-sukka-dosa", "Mutton Sukka with Dosa", "மட்டன் சுக்கா தோசை", ["dinner"], "onepot", 30,
    ["Mutton", "Onion, spices", "Coconut", "Curry leaves", "Dosa"],
    ["Cook mutton.", "Saute dry with masala.", "Serve with dosa."]),
  mk("grilled-fish-rice", "Grilled Fish with Rice", "மீன் வறுவல் சாதம்", ["dinner"], "onepot", 26,
    ["Fish", "Chilli, turmeric", "Ginger garlic", "Lemon", "Rice"],
    ["Marinate fish.", "Grill till done.", "Serve with rice."]),
  mk("ragi-kali", "Ragi Kali with Kuzhambu", "ராகி களி", ["dinner"], "onepot", 9,
    ["Ragi flour", "Water", "Salt", "Spicy kuzhambu"],
    ["Cook ragi to a stiff mass.", "Shape portions.", "Serve with kuzhambu."]),
  mk("kambu-koozh", "Kambu Koozh", "கம்பு கூழ்", ["dinner"], "onepot", 8,
    ["Pearl millet flour", "Buttermilk", "Rice", "Salt", "Small onion"],
    ["Cook millet to a porridge.", "Mix with buttermilk.", "Serve with onion and pickle."]),
  mk("lemon-sevai", "Lemon Sevai", "எலுமிச்சை சேவை", ["dinner"], "onepot", 7,
    ["Rice sevai", "Lemon", "Peanuts", "Dals", "Turmeric"],
    ["Prepare sevai.", "Temper dals and peanuts.", "Toss with lemon.", "Serve."]),
  mk("coconut-sevai", "Coconut Sevai", "தேங்காய் சேவை", ["dinner"], "onepot", 7,
    ["Rice sevai", "Coconut", "Cashews", "Dals", "Chilli"],
    ["Prepare sevai.", "Temper dals and cashews.", "Toss with coconut.", "Serve."]),
  mk("keerai-masiyal-rice", "Keerai Masiyal with Rice", "கீரை மசியல் சாதம்", ["dinner"], "onepot", 10,
    ["Spinach", "Moong dal", "Garlic", "Cumin, chilli", "Rice"],
    ["Cook spinach with dal.", "Mash and temper.", "Serve with rice."]),
];

export const SEED_DISHES: Dish[] = [
  ...CHUTNEYS,
  ...SAMBARS,
  ...RICE,
  ...RASAMS,
  ...CURDS,
  ...BREAKFAST,
  ...KUZHAMBU,
  ...LUNCH_ONEPOT,
  ...POROYAL,
  ...DINNER_TIFFIN,
  ...DINNER_ONEPOT,
];
